[versions]
agp = "8.13.2"
kotlin = "2.0.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.12.2"
constraintlayout = "2.2.1"
nav_version = "2.9.6"
serialization = "2.0.21"
recyclerview = "1.4.0"
recyclerviewselection= "1.2.0"
viewmodel="2.6.2"
fragment = "1.6.2"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-navigation-compose = {group = "androidx.navigation", name="navigation-compose", version.ref= "nav_version"}
androidx-navigation-fragment = { group = "androidx.navigation", name="navigation-fragment",version.ref= "nav_version"}
androidx-navigation-ui = {group = "androidx.navigation", name="navigation-ui", version.ref="nav_version"}
androidx-navigation-dynamic-features-fragment = {group ="androidx.navigation",name="navigation-dynamic-features-fragment",version.ref = "nav_version"}
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }
androidx-recyclerview = {group="androidx.recyclerview", name="recyclerview", version.ref="recyclerview"}
androidx-recyclerview-selection = {group="androidx.recyclerview", name="recyclerview-selection", version.ref="recyclerviewselection"}
androidx-lifecycle-viewmodel-ktx = {group="androidx.lifecycle", name="lifecycle-viewmodel-ktx",version.ref="viewmodel"}
androidx-lifecycle-livedata-ktx = {group="androidx.lifecycle", name="lifecycle-livedata-ktx", version.ref="viewmodel"}
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragment" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
navigation-safe-args= { id= "androidx.navigation.safeargs.kotlin" , version.ref= "nav_version"}

